### ISSUE TITLE
What happened to Gaia Steve ?!

### ISSUE THREAD

**Issue by Cramredan** [stevensacks/Gaia-Framework#3]
With such a move to GitHub, the disappeared great Gaia Framework website and all its related forums and references, the unsupported CS6 etc... the whole Gaia Framework seems to have vanished suddenly as if it did never exist. The plain Internet miracle !!!

What happened Steven ???

You're 100% free to decide to "resign" from your Gaia lifetime works, but you're morally tied to inform the community relying on your framework.

Not a single word, no news or explanations found anywhere. This is simply incredible. >>>>  P.L.E.A.S.E INFORM US <<<<

**Comment by ghost** [comment]
7 months, no respond. He use to respond instantly at the closed forum.

**Comment by ghost** [comment]
woow, 1 more year, no respond.

**Comment by Cramredan** [comment]
Dead ! Or hired by DARPA … A real shame !!!

De : Emrah Atılkan [mailto:notifications@github.com] 
Envoyé : lundi 5 janvier 2015 08:25
À : stevensacks/Gaia-Framework
Cc : Cramredan
Objet : Re: [Gaia-Framework] What happened to Gaia Steve ?! (#3)

woow, 1 more year, no respond.

**Comment by VladimirCores** [comment]
It's sad

**Comment by ghost** [comment]
2 more months. In fact i don't use flash to build sites any more and the framework became no point even it was wonderful, full of great features. So there is no need to work on that. 
We can move on.

**Comment by ghost** [comment]
5 more months. We will get old.

**Comment by ghost** [comment]
finally, after 2,5 years.

**Comment by Cramredan** [comment]
At least, after nearly 2.5 years of covered operations, he is still alive. Good news Steven. Enjoy!

De : Atılkan [mailto:notifications@github.com] 
Envoyé : mardi 20 octobre 2015 13:52
À : stevensacks/Gaia-Framework
Cc : Cramredan
Objet : Re: [Gaia-Framework] What happened to Gaia Steve ?! (#3)

finally, after 2,5 years.
