### ISSUE TITLE
Gaia Framework Down

### ISSUE THREAD

**Issue by Aurorans** [stevensacks/Gaia-Framework#6]
It's down at http://www.gaiaflashframework.com

Also, your own personal website is down. http://www.stevensacks.net 

This is affecting millions of users on NCAA football 14, as EA sports uses Gaia Flash Framework for their NCAA football 14 teambuilder website.

Any chance on seeing this return?

**Comment by stevensacks** [comment]
Unfortunately, no. Those domains have expired. The Gaia Flash Framework panel source code is open source and has already been modified to not require a token. The version check can be disabled, as well here:

https://github.com/stevensacks/Gaia-Framework/blob/master/panel/src/com/gaiaframework/panel/services/VersionService.as

The project will have to be recompiled again using FlexBuilder. I don't personally have a copy of it anymore. It's been years.
